---
# Common Setup

#
# -----------------------------------------------------------------------------
# Install docker (engine)
# -----------------------------------------------------------------------------
#
- name: Install Docker
  yum:
    name: "{{ serapeum_docker_service_name }}"
    state: present
    when: ansible_os_family == "RedHat"
    register: "docker_installed"

#
# -----------------------------------------------------------------------------
# Enable and Start Docker
# -----------------------------------------------------------------------------
#
- name: Enable and Start Docker
  service:
      name: "{{ serapeum_docker_service_name }}"
      state: started
      enabled: yes
      when:
        - ansible_os_family == "RedHat"
        - docker_installed
      register: "docker_started"

#
# -----------------------------------------------------------------------------
# Install docker.py Docker API Python Library
# -----------------------------------------------------------------------------
#
- name: Install docker.py
  yum:
    name: "{{ serapeum_docker_py_name }}"
    state: present
    when: ansible_os_family == "RedHat"
    register: "docker_py_installed"
