---
# Common Tasks

#
# -----------------------------------------------------------------------------
# Load vars
# -----------------------------------------------------------------------------
#
- name: Load OS Specific Vars
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-7
    - "{{ ansible_distribution }}.yaml"                                             # RedHat.yaml or CentOS.yaml
    - "{{ ansible_os_family }}.yaml"                                                # RedHat.yaml
    - "default.yml"

#
# -----------------------------------------------------------------------------
# Load OCP vars if enabled
# -----------------------------------------------------------------------------
#
- name: Load OCP Specific Vars
  include_vars: "{{ item }}"
    file: "OCP_{{ serapeum_openshift_version }}.yaml"
  when: serapeum_openshift_enabled
