---
# Install and Populate Registry

#
# -----------------------------------------------------------------------------
# Install docker-distribution RPM
# -----------------------------------------------------------------------------
#
- name: Install Registry
  yum:
    name: "{{ serapeum_registry_service_name }}"
    state: present
    register: "registry_installed"

#
# -----------------------------------------------------------------------------
# Enable and Start Registry
# -----------------------------------------------------------------------------
#
- name: Enable and Start Registry
  service:
      name: "{{ serapeum_registry_service_name }}"
      state: started
      enabled: yes
      when:
        - "{{ serapeum_registry_service_name }}_installed"
        - registry_installed
      register: "registry_started"

# Load Offline Tarball
#- name: Docker Load Offline Tarball
#  docker_image:
#    load_path: {{ serapeum_offline_images_dir }}

#
# -----------------------------------------------------------------------------
# Load, Tag and Upload to Registry
# -----------------------------------------------------------------------------
#
- name: Load, Tag and Upload Images to Registry
  docker_image:
    name: "{{ serapeum_registry_host }}:{{ serapeum_registry_port }}/{{ item.name }}"
    tag: "{{ item.tag }}"
    push: yes
    load_path: "{{ serapeum_offline_images_dir }}/{{ item }}.tar"
  with_items:
  - "{{ serapeum_ocp_base_images }}"
  - "{{ serapeum_ocp_logging_metrics_images }}"
  register: images_uploaded
