---
# Download & Archive Specified Docker Images

#
# -----------------------------------------------------------------------------
# Download Docker Images from repos
# -----------------------------------------------------------------------------
#
- name: Pull Docker Images
  docker_image:
    name: "{{ item.repository }}/{{ item.name }}"
    tag: "{{ item.tag }}"
  with_items:
  - "{{ serapeum_docker_images }}"
  register: docker_images_pulled

#
# -----------------------------------------------------------------------------
# Create temp dir
# -----------------------------------------------------------------------------
#
- name: Create Images Export Directory
  file:
    path: "{{ serapeum_offline_images_dir }}"
    state: directory
    mode: 0777
  register: temp_dir_created

#
# -----------------------------------------------------------------------------
# Archive Docker Images to Tarball
# -----------------------------------------------------------------------------
#
- name: Save Images to Tarball
  docker_image:
    name: "{{ item.repository }}/{{ item.namespace | default(omit) }}/{{ item.name }}"
    archive_path: "{{ serapeum_offline_images_dir }}/{{ serapeum_docker_offline_images_tarball }}"
    tag: "{{ item.tag }}"
  with_items:
  - "{{ serapeum_docker_images }}"
  when: docker_images_pulled
  register: docker_images_saved

- name: Remove Previous Tarball if Exists
  file:
    path: "{{ serapeum_offline_images_dir }}/{{ serapeum_docker_offline_images_tarball }}"
    state: absent

- name: Set Fact of All Images for Docker Save
  set_fact:
    serapeum_docker_images_fullname: "{{ serapeum_docker_images| }}"

- name: Debug serapeum_docker_images_fullname
  debug: msg="{{ serapeum_docker_images_fullname }}"

- name: Archive Images to Tarball
  command: "/usr/bin/docker save -o {{ serapeum_docker_offline_images_tarball }} {{ item }}"
  with_items:
    - "{{ serapeum_docker_images }}"
  when:
    - docker_images_pulled
  register: docker_images_archived

#
# -----------------------------------------------------------------------------
# Verify Tarball
# -----------------------------------------------------------------------------
#
- name: Verify Docker Image Tarball File Exists
  stat:
    path: "{{ serapeum_offline_images_dir }}/{{ serapeum_docker_offline_images_tarball }}"
  register: docker_tarball

- name: Fail if Tarball Does Not Exist
  fail:
    msg: "Docker Image Tarball {{ serapeum_offline_images_dir }}/{{ serapeum_docker_offline_images_tarball }} Does Not Exist"
  when: docker_tarball.stat.exists == false

- name: Success if Tarball Does Exist
  debug:
    msg: "Docker Image Tarball {{ serapeum_offline_images_dir }}/{{ serapeum_docker_offline_images_tarball }} Exists"
  when: docker_tarball.stat.exists == true
  register: docker_tarball_exists
