---
# Tasks file for ansible-serapeum

#
# -----------------------------------------------------------------------------
# Common Tasks
# -----------------------------------------------------------------------------
#
- include: common.yaml

#
# -----------------------------------------------------------------------------
# Docker Tasks
# -----------------------------------------------------------------------------
#
- include: docker_el.yaml
  when:
  - ansible_os_family == "RedHat"

#
# -----------------------------------------------------------------------------
# Download and Prepare Images
# -----------------------------------------------------------------------------
#
- include: images_prepare.yaml
  when: serapeum_stage_prepare

#
# -----------------------------------------------------------------------------
# Deploy Registry
# -----------------------------------------------------------------------------
#
- include: registry_el.yaml
  when:
  - serapeum_stage_deploy
  - ansible_os_family == "RedHat"

#
# -----------------------------------------------------------------------------
# Populate Registry
# -----------------------------------------------------------------------------
#
- include: images_populate.yaml
  when: serapeum_stage_deploy
