---
# Tasks file for ansible-serapeum

#
# -----------------------------------------------------------------------------
# Common Tasks
# -----------------------------------------------------------------------------
#
- include: common.yaml

#
# -----------------------------------------------------------------------------
# Download and Prepare Images
# -----------------------------------------------------------------------------
#
- include: download_prepare.yaml
  when: serapeum_stage_prepare

#
# -----------------------------------------------------------------------------
# Deploy Registry and Populate
# -----------------------------------------------------------------------------
#
- include: deploy_populate.yaml
  when: serapeum_stage_deploy
