---
# Tasks file for ansible-serapeum

#
# -----------------------------------------------------------------------------
# Common Tasks
# -----------------------------------------------------------------------------
#
- include: common.yaml
  tags: [prepare,populate,openshift]

#
# -----------------------------------------------------------------------------
# Docker Tasks
# -----------------------------------------------------------------------------
#
- include: docker_el.yaml
  when:
  - ansible_os_family == "RedHat"
  tags: [prepare,populate,openshift]

#
# -----------------------------------------------------------------------------
# Download and Prepare Images
# -----------------------------------------------------------------------------
#
- include: images_prepare.yaml
#  when: serapeum_stage_prepare
  tags: [prepare]

- include: ocp_images_prepare.yaml
  when:
#    - serapeum_stage_prepare
    - serapeum_openshift_enabled
  tags: [prepare,openshift]

#
# -----------------------------------------------------------------------------
# Deploy Registry
# -----------------------------------------------------------------------------
#
- include: registry_el.yaml
  when:
#  - serapeum_stage_populate
  - ansible_os_family == "RedHat"
  tags: [populate]

#
# -----------------------------------------------------------------------------
# Populate Registry
# -----------------------------------------------------------------------------
#
- include: images_populate.yaml
#  when: serapeum_stage_populate
  tags: [populate]

- include: ocp_images_populate.yaml
  when:
#  - serapeum_stage_populate
  - serapeum_openshift_enabled
  tags: [populate,openshift]
