---
# Load, Tag & Upload Specified OCP Images

#
# -----------------------------------------------------------------------------
# Verify Tarball
# -----------------------------------------------------------------------------
#
#- name: Verify OCP Image Tarball File Exists
#  stat:
#    path: "{{ serapeum_offline_images_dir }}/{{ serapeum_ocp_offline_images_tarball }}"
#  register: ocp_tarball

#- name: Fail if Tarball Does Not Exist
#  fail:
#    msg: "OCP Image Tarball {{ serapeum_offline_images_dir }}/{{ serapeum_ocp_offline_images_tarball }} Does Not Exist"
#  when: ocp_tarball.stat.exists == false

#- name: Success if Tarball Does Exist
#  debug:
#    msg: "OCP Image Tarball {{ serapeum_offline_images_dir }}/{{ serapeum_ocp_offline_images_tarball }} Exists"
#  when: ocp_tarball.stat.exists == true
#  register: ocp_tarball_exists

#
# -----------------------------------------------------------------------------
# Load and Tag Offline OCP Images from Tarball
# -----------------------------------------------------------------------------
#
- name: Load, Tag and Push Offline OCP Images Tarball
  docker_image:
    name: "{{ item.repository }}{{ (item.namespace == None) | ternary('', '/')  }}{{ item.namespace }}/{{ item.name}}"
    tag: "{{ item.tag }}"
    repository: "{{ serapeum_registry_hostname }}:{{ serapeum_registry_port }}{{ (item.namespace == None) | ternary('', '/')  }}{{ item.namespace }}/{{ item.name }}"
    load_path: "{{ serapeum_offline_images_dir }}/ocp_image_{{ item.name }}.tar"
  with_items:
#  - "{{ serapeum_ocp_base_images }}"
  - "{{ serapeum_ocp_extra_images }}"
#  - "{{ serapeum_ocp_logging_metrics_images }}"
#  when:
#  - "{{ serapeum_offline_images_dir }}/ocp_image_{{ item.name }}.tar"
#  - ocp_tarball_exists
  register: ocp_images_loaded


#
# -----------------------------------------------------------------------------
# Upload OCP Images to Registry
# -----------------------------------------------------------------------------
#
#- name: Upload OCP Images to Registry
#  docker_image:
#    name: "{{ item.name }}"
#    tag: "{{ item.tag }}"
#    push: yes
#    repository: "{{ serapeum_registry_hostname }}:{{ serapeum_registry_port }}{{ (item.namespace == None) | ternary('', '/')  }}{{ item.namespace }}/{{ item.name }}"
#  with_items:
#  - "{{ serapeum_ocp_base_images }}"
#  - "{{ serapeum_ocp_extra_images }}"
#  - "{{ serapeum_ocp_logging_metrics_images }}"
#  when:
#      - registry_started
#      - ocp_images_loaded
#  register: ocp_images_uploaded
