---
# Registry Tasks

#
# -----------------------------------------------------------------------------
# Install Registry (docker-distribution RPM)
# -----------------------------------------------------------------------------
#
- name: Install Registry
  yum:
    name: "{{ serapeum_registry_service_name }}"
    state: present
  when: ansible_os_family == "RedHat"
  register: registry_installed

#
# -----------------------------------------------------------------------------
# Enable and Start Registry
# -----------------------------------------------------------------------------
#
- name: Enable and Start Registry
  service:
    name: "{{ serapeum_registry_service_name }}"
    state: started
    enabled: yes
  when:
    - ansible_os_family == "RedHat"
    - registry_installed
  register: registry_started
