---
# Registry Tasks

#
# -----------------------------------------------------------------------------
# Install Registry (docker-distribution RPM)
# -----------------------------------------------------------------------------
#
- name: Install Registry
  yum:
    name: "{{ serapeum_registry_service_name }}"
    state: present
  when: ansible_os_family == "RedHat"
  register: registry_installed

#
# -----------------------------------------------------------------------------
# Configure Local Registry as Insecure /etc/sysconfig/docker
# -----------------------------------------------------------------------------
#
- name: Set Registry Params
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^{{ item.reg_conf_var }}=.*$'
    line: "{{ item.reg_conf_var }}='{{ item.reg_fact_val | oo_prepend_strings_in_list(item.reg_flag ~ ' ') | join(' ') }}'"
  when: item.reg_fact_val != '' and docker_check.stat.isreg is defined and docker_check.stat.isreg
  with_items:
  - reg_conf_var: ADD_REGISTRY
    reg_fact_val: "{{ serapeum_additional_registries | default(None, true)}}"
    reg_flag: --add-registry
  - reg_conf_var: BLOCK_REGISTRY
    reg_fact_val: "{{ serapeum_blocked_registries| default(None, true) }}"
    reg_flag: --block-registry
  - reg_conf_var: INSECURE_REGISTRY
    reg_fact_val: "{{ serapeum_insecure_registries| default(None, true) }}"
    reg_flag: --insecure-registry
  notify:
  - Restart Docker
  - Restart Registry


#
# -----------------------------------------------------------------------------
# Enable and Start Registry
# -----------------------------------------------------------------------------
#
- name: Enable and Start Registry
  service:
    name: "{{ serapeum_registry_service_name }}"
    state: started
    enabled: yes
  when:
    - ansible_os_family == "RedHat"
    - registry_installed
  register: registry_started
