---
# handlers file for ansible-serapeum

# Restart Docker
- name: Restart Docker
  service:
    name: "{{ serapeum_docker_service_name }}"
    state: restarted

# Restart Registry
- name: Restart Registry
  service:
    name: "{{ serapeum_registry_service_name }}"
    state: restarted
