---
# handlers file for ansible-serapeum

# Restart Docker
- name: Restarting Docker
  service: "name={{ serapeum_docker_service_name }} state=restarted"

# Restart Registry
- name: Restarting Registry
  service: "name={{ serapeum_registry_service_name }} state=restarted"
